apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: quay.io/instaclustr
  tag: latest
  revision: 1-8-0
  namespace: instaclustr-istio
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    egressGateways:
    - name: base-egressgateway
      enabled: true
    ingressGateways:
    - name: base-ingressgateway
      enabled: true